# Generated by Django 3.1.6 on 2021-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('Title', models.CharField(default='', max_length=30)),
                ('Course_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Instructor_Name', models.CharField(default='', max_length=50)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
