# Generated by Django 3.1.6 on 2021-02-18 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Starting_Balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Description', models.CharField(max_length=100)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkbook.account')),
            ],
        ),
    ]
